Select * from OSOBA;
CREATE TABLE OSOBA (
    ID INT PRIMARY KEY,
    IMIE VARCHAR(255) NOT NULL,
    NAZWISKO VARCHAR(255) NOT NULL,
    PLEC CHAR(1) NOT NULL
);
CREATE SEQUENCE OSOBA_SEQ
    START WITH 1
    INCREMENT BY 1;

DECLARE @next_id INT
SELECT @next_id = NEXT VALUE FOR OSOBA_SEQ

INSERT INTO OSOBA (ID, IMIE, NAZWISKO, PLEC)
VALUES (@next_id, 'Jan2', 'Kowalski2', 'M');

----------------------
CREATE TABLE OSOBA2 (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    IMIE VARCHAR(50) NOT NULL,
    NAZWISKO VARCHAR(50) NOT NULL,
    PLEC CHAR(1) NOT NULL
);
Select * from Osoba2
INSERT INTO OSOBA2 (IMIE, NAZWISKO, PLEC)
VALUES ('Jan23', 'Kowalski32', 'M');

